---
title: "R Objects, Workflow and Functions"
format: html
editor: visual
---

# Vectors

Create a vector

```{r}
set.seed(42)
my_unif <- runif(30)
is.vector(my_unif)
```

Subset that object

```{r}
my_unif[1:10]

my_unif[c(1:3, 15:17)]
```


Sort the vector 

```{r}
sort(my_unif)
```


Create a vector with strings in it

```{r}
char_vec <- c('daf', "adf", "e2", '13da')
sort(char_vec)
```

# Data Frame

```{r}
data(trees)
trees
str(trees)
```

Subset a Column

```{r}
trees$Height
```

Get attributes from the data frame

```{r}
attributes(trees)
names(trees)
colnames(trees)[2:3]
```

# Lists

Investigating data frame from before

```{r}
is.list(trees)
is.data.frame(trees)
```

Can subset as a list

```{r}
trees[1]
trees[[1]]
```

Look at linear model fit

```{r}
fit <- lm(Volume ~ Height + Girth, data = trees)
```

Look at structure but restrict info

```{r}
str(fit, max.level = 1)
```

Some helper functions exist

```{r}
fit$coefficients
coef(fit)

#no helper function for rank: rank(fit)
```

